"""init clean

Revision ID: 1985c7bdaeee
Revises: 
Create Date: 2026-04-25 01:19:11.187974

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1985c7bdaeee'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problem',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=140), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=600), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problem_slug'), 'problem', ['slug'], unique=False)
    op.create_index('uq_problem_slug_active', 'problem', ['slug'], unique=True, sqlite_where=sa.text('state = 1'), postgresql_where=sa.text('state = true'))
    op.create_table('services',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=90), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_slug'), 'services', ['slug'], unique=False)
    op.create_index('uq_service_slug_active', 'services', ['slug'], unique=True, sqlite_where=sa.text('state = 1'), postgresql_where=sa.text('state = true'))
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'OWNER', 'MECHANIC', 'CLIENT', name='userrole'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('vehicle_type',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.Column('name', sa.Enum('CAR', 'MOTORCYCLE', 'TRUCK', name='vehicletypename'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_type_name'), 'vehicle_type', ['name'], unique=False)
    op.create_index('uq_vehicle_type_name_active', 'vehicle_type', ['name'], unique=True, sqlite_where=sa.text('state = 1'), postgresql_where=sa.text('state = true'))
    op.create_table('problem_service_map',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.Column('problem_id', sa.Uuid(), nullable=False),
    sa.Column('service_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problem_service_map_problem_id'), 'problem_service_map', ['problem_id'], unique=False)
    op.create_index(op.f('ix_problem_service_map_service_id'), 'problem_service_map', ['service_id'], unique=False)
    op.create_index('uq_problem_service_map_active', 'problem_service_map', ['problem_id', 'service_id'], unique=True, sqlite_where=sa.text('state = 1'), postgresql_where=sa.text('state = true'))
    op.create_table('repair_shop',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=70), nullable=False),
    sa.Column('text_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repair_shop_name'), 'repair_shop', ['name'], unique=False)
    op.create_index(op.f('ix_repair_shop_owner_id'), 'repair_shop', ['owner_id'], unique=False)
    op.create_index('uq_shop_name_active', 'repair_shop', ['name'], unique=True, sqlite_where=sa.text('state = 1'), postgresql_where=sa.text('state = true'))
    op.create_table('vehicle',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.Column('make', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('plate', sqlmodel.sql.sqltypes.AutoString(length=12), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['vehicle_type.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_plate'), 'vehicle', ['plate'], unique=False)
    op.create_index(op.f('ix_vehicle_type_id'), 'vehicle', ['type_id'], unique=False)
    op.create_index(op.f('ix_vehicle_user_id'), 'vehicle', ['user_id'], unique=False)
    op.create_index('uq_vehicle_plate_active', 'vehicle', ['plate'], unique=True, sqlite_where=sa.text('state = 1'), postgresql_where=sa.text('state = true'))
    op.create_table('incident',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CLASSIFYING', 'CLASSIFIED', 'SEARCHING_SHOP', 'ASSIGNED', 'ON_THE_WAY', 'ARRIVED', 'COMPLETED', 'CANCELLED', 'FAILED', name='incidentstatus'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='incidentpriority'), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('ai_attempts', sa.Integer(), nullable=False),
    sa.Column('delivery_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('distance_km', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('problem_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_problem_id'), 'incident', ['problem_id'], unique=False)
    op.create_index(op.f('ix_incident_status'), 'incident', ['status'], unique=False)
    op.create_index(op.f('ix_incident_user_id'), 'incident', ['user_id'], unique=False)
    op.create_index(op.f('ix_incident_vehicle_id'), 'incident', ['vehicle_id'], unique=False)
    op.create_table('shop_mechanics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('shop_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['repair_shop.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_mechanics_shop_id'), 'shop_mechanics', ['shop_id'], unique=False)
    op.create_index(op.f('ix_shop_mechanics_user_id'), 'shop_mechanics', ['user_id'], unique=False)
    op.create_index('uq_shop_mechanic_user_active', 'shop_mechanics', ['user_id'], unique=True, sqlite_where=sa.text('state = 1'), postgresql_where=sa.text('state = true'))
    op.create_table('shop_services',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('shop_id', sa.Uuid(), nullable=False),
    sa.Column('service_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['repair_shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_services_service_id'), 'shop_services', ['service_id'], unique=False)
    op.create_index(op.f('ix_shop_services_shop_id'), 'shop_services', ['shop_id'], unique=False)
    op.create_index('uq_shop_service_active', 'shop_services', ['service_id', 'shop_id'], unique=True, sqlite_where=sa.text('state = 1'), postgresql_where=sa.text('state = true'))
    op.create_table('shopinvitation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('shop_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['repair_shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shopinvitation_code'), 'shopinvitation', ['code'], unique=False)
    op.create_index(op.f('ix_shopinvitation_shop_id'), 'shopinvitation', ['shop_id'], unique=False)
    op.create_index('uq_shop_invitation_active', 'shopinvitation', ['shop_id'], unique=True, sqlite_where=sa.text('state = 1'), postgresql_where=sa.text('state = true'))
    op.create_table('wallet',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('repair_shop_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['repair_shop_id'], ['repair_shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_repair_shop_id'), 'wallet', ['repair_shop_id'], unique=False)
    op.create_index('uq_wallet_repair_shop_active', 'wallet', ['repair_shop_id'], unique=True, sqlite_where=sa.text('state = 1'), postgresql_where=sa.text('state = true'))
    op.create_table('incident_evidence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_evidence_incident_id'), 'incident_evidence', ['incident_id'], unique=False)
    op.create_table('request_assignment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('repair_shop_id', sa.Uuid(), nullable=False),
    sa.Column('mechanic_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'CANCELLED', 'EXPIRED', 'COMPLETED', 'FAILED', name='assignmentstatus'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], ),
    sa.ForeignKeyConstraint(['mechanic_id'], ['shop_mechanics.id'], ),
    sa.ForeignKeyConstraint(['repair_shop_id'], ['repair_shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_assignment_incident_id'), 'request_assignment', ['incident_id'], unique=False)
    op.create_index(op.f('ix_request_assignment_mechanic_id'), 'request_assignment', ['mechanic_id'], unique=False)
    op.create_index(op.f('ix_request_assignment_repair_shop_id'), 'request_assignment', ['repair_shop_id'], unique=False)
    op.create_index(op.f('ix_request_assignment_status'), 'request_assignment', ['status'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.Column('type', sa.Enum('TOPUP', 'DEBIT_SERVICE', 'REFUND', 'ADJUSTMENT', name='transactiontype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'POSTED', 'FAILED', 'REVERSED', name='transactionstatus'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('balance_before', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=280), nullable=True),
    sa.Column('wallet_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_status'), 'transactions', ['status'], unique=False)
    op.create_index(op.f('ix_transactions_type'), 'transactions', ['type'], unique=False)
    op.create_index(op.f('ix_transactions_wallet_id'), 'transactions', ['wallet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_wallet_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_type'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_status'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_request_assignment_status'), table_name='request_assignment')
    op.drop_index(op.f('ix_request_assignment_repair_shop_id'), table_name='request_assignment')
    op.drop_index(op.f('ix_request_assignment_mechanic_id'), table_name='request_assignment')
    op.drop_index(op.f('ix_request_assignment_incident_id'), table_name='request_assignment')
    op.drop_table('request_assignment')
    op.drop_index(op.f('ix_incident_evidence_incident_id'), table_name='incident_evidence')
    op.drop_table('incident_evidence')
    op.drop_index('uq_wallet_repair_shop_active', table_name='wallet', sqlite_where=sa.text('state = 1'), postgresql_where=sa.text('state = true'))
    op.drop_index(op.f('ix_wallet_repair_shop_id'), table_name='wallet')
    op.drop_table('wallet')
    op.drop_index('uq_shop_invitation_active', table_name='shopinvitation', sqlite_where=sa.text('state = 1'), postgresql_where=sa.text('state = true'))
    op.drop_index(op.f('ix_shopinvitation_shop_id'), table_name='shopinvitation')
    op.drop_index(op.f('ix_shopinvitation_code'), table_name='shopinvitation')
    op.drop_table('shopinvitation')
    op.drop_index('uq_shop_service_active', table_name='shop_services', sqlite_where=sa.text('state = 1'), postgresql_where=sa.text('state = true'))
    op.drop_index(op.f('ix_shop_services_shop_id'), table_name='shop_services')
    op.drop_index(op.f('ix_shop_services_service_id'), table_name='shop_services')
    op.drop_table('shop_services')
    op.drop_index('uq_shop_mechanic_user_active', table_name='shop_mechanics', sqlite_where=sa.text('state = 1'), postgresql_where=sa.text('state = true'))
    op.drop_index(op.f('ix_shop_mechanics_user_id'), table_name='shop_mechanics')
    op.drop_index(op.f('ix_shop_mechanics_shop_id'), table_name='shop_mechanics')
    op.drop_table('shop_mechanics')
    op.drop_index(op.f('ix_incident_vehicle_id'), table_name='incident')
    op.drop_index(op.f('ix_incident_user_id'), table_name='incident')
    op.drop_index(op.f('ix_incident_status'), table_name='incident')
    op.drop_index(op.f('ix_incident_problem_id'), table_name='incident')
    op.drop_table('incident')
    op.drop_index('uq_vehicle_plate_active', table_name='vehicle', sqlite_where=sa.text('state = 1'), postgresql_where=sa.text('state = true'))
    op.drop_index(op.f('ix_vehicle_user_id'), table_name='vehicle')
    op.drop_index(op.f('ix_vehicle_type_id'), table_name='vehicle')
    op.drop_index(op.f('ix_vehicle_plate'), table_name='vehicle')
    op.drop_table('vehicle')
    op.drop_index('uq_shop_name_active', table_name='repair_shop', sqlite_where=sa.text('state = 1'), postgresql_where=sa.text('state = true'))
    op.drop_index(op.f('ix_repair_shop_owner_id'), table_name='repair_shop')
    op.drop_index(op.f('ix_repair_shop_name'), table_name='repair_shop')
    op.drop_table('repair_shop')
    op.drop_index('uq_problem_service_map_active', table_name='problem_service_map', sqlite_where=sa.text('state = 1'), postgresql_where=sa.text('state = true'))
    op.drop_index(op.f('ix_problem_service_map_service_id'), table_name='problem_service_map')
    op.drop_index(op.f('ix_problem_service_map_problem_id'), table_name='problem_service_map')
    op.drop_table('problem_service_map')
    op.drop_index('uq_vehicle_type_name_active', table_name='vehicle_type', sqlite_where=sa.text('state = 1'), postgresql_where=sa.text('state = true'))
    op.drop_index(op.f('ix_vehicle_type_name'), table_name='vehicle_type')
    op.drop_table('vehicle_type')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index('uq_service_slug_active', table_name='services', sqlite_where=sa.text('state = 1'), postgresql_where=sa.text('state = true'))
    op.drop_index(op.f('ix_services_slug'), table_name='services')
    op.drop_table('services')
    op.drop_index('uq_problem_slug_active', table_name='problem', sqlite_where=sa.text('state = 1'), postgresql_where=sa.text('state = true'))
    op.drop_index(op.f('ix_problem_slug'), table_name='problem')
    op.drop_table('problem')
    # ### end Alembic commands ###
