"""modifies

Revision ID: 1f76da8c05c8
Revises: fcfb9293fd61
Create Date: 2026-04-27 23:27:45.448674

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f76da8c05c8'
down_revision: Union[str, Sequence[str], None] = 'fcfb9293fd61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_assignment', sa.Column('estimated_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request_assignment', 'estimated_minutes')
    # ### end Alembic commands ###
