"""modified queue logic model

Revision ID: 261ddf1a49e3
Revises: 28b9f1de5aea
Create Date: 2026-04-25 22:14:04.383012

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '261ddf1a49e3'
down_revision: Union[str, Sequence[str], None] = '28b9f1de5aea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_assignment', sa.Column('queue_rank', sa.Integer(), nullable=True))
    op.add_column('request_assignment', sa.Column('offered_at', sa.DateTime(), nullable=True))
    op.add_column('request_assignment', sa.Column('notified_at', sa.DateTime(), nullable=True))
    op.add_column('request_assignment', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.add_column('request_assignment', sa.Column('responded_at', sa.DateTime(), nullable=True))
    op.add_column('request_assignment', sa.Column('notification_attempts', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_request_assignment_expires_at'), 'request_assignment', ['expires_at'], unique=False)
    op.create_index(op.f('ix_request_assignment_notified_at'), 'request_assignment', ['notified_at'], unique=False)
    op.create_index(op.f('ix_request_assignment_queue_rank'), 'request_assignment', ['queue_rank'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_request_assignment_queue_rank'), table_name='request_assignment')
    op.drop_index(op.f('ix_request_assignment_notified_at'), table_name='request_assignment')
    op.drop_index(op.f('ix_request_assignment_expires_at'), table_name='request_assignment')
    op.drop_column('request_assignment', 'notification_attempts')
    op.drop_column('request_assignment', 'responded_at')
    op.drop_column('request_assignment', 'expires_at')
    op.drop_column('request_assignment', 'notified_at')
    op.drop_column('request_assignment', 'offered_at')
    op.drop_column('request_assignment', 'queue_rank')
    # ### end Alembic commands ###
