"""modififed request assingment

Revision ID: 28b9f1de5aea
Revises: 84f6ce9ac9d2
Create Date: 2026-04-25 21:17:56.724378

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28b9f1de5aea'
down_revision: Union[str, Sequence[str], None] = '84f6ce9ac9d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
