"""tables for live events

Revision ID: a0e566a3824e
Revises: 261ddf1a49e3
Create Date: 2026-04-26 11:16:03.435232

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0e566a3824e'
down_revision: Union[str, Sequence[str], None] = '261ddf1a49e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident_realtime_event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_realtime_event_event_type'), 'incident_realtime_event', ['event_type'], unique=False)
    op.create_index(op.f('ix_incident_realtime_event_incident_id'), 'incident_realtime_event', ['incident_id'], unique=False)
    op.create_table('incident_live_state',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=True),
    sa.Column('assignment_id', sa.Uuid(), nullable=True),
    sa.Column('repair_shop_id', sa.Uuid(), nullable=True),
    sa.Column('mechanic_id', sa.Uuid(), nullable=True),
    sa.Column('mechanic_latitude', sa.Float(), nullable=True),
    sa.Column('mechanic_longitude', sa.Float(), nullable=True),
    sa.Column('mechanic_location_updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_event_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['request_assignment.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], ),
    sa.ForeignKeyConstraint(['mechanic_id'], ['shop_mechanics.id'], ),
    sa.ForeignKeyConstraint(['repair_shop_id'], ['repair_shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_live_state_assignment_id'), 'incident_live_state', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_incident_live_state_incident_id'), 'incident_live_state', ['incident_id'], unique=True)
    op.create_index(op.f('ix_incident_live_state_mechanic_id'), 'incident_live_state', ['mechanic_id'], unique=False)
    op.create_index(op.f('ix_incident_live_state_repair_shop_id'), 'incident_live_state', ['repair_shop_id'], unique=False)
    op.create_index(op.f('ix_incident_live_state_status'), 'incident_live_state', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incident_live_state_status'), table_name='incident_live_state')
    op.drop_index(op.f('ix_incident_live_state_repair_shop_id'), table_name='incident_live_state')
    op.drop_index(op.f('ix_incident_live_state_mechanic_id'), table_name='incident_live_state')
    op.drop_index(op.f('ix_incident_live_state_incident_id'), table_name='incident_live_state')
    op.drop_index(op.f('ix_incident_live_state_assignment_id'), table_name='incident_live_state')
    op.drop_table('incident_live_state')
    op.drop_index(op.f('ix_incident_realtime_event_incident_id'), table_name='incident_realtime_event')
    op.drop_index(op.f('ix_incident_realtime_event_event_type'), table_name='incident_realtime_event')
    op.drop_table('incident_realtime_event')
    # ### end Alembic commands ###
