"""New models

Revision ID: fcfb9293fd61
Revises: c13b0c9de31f
Create Date: 2026-04-27 17:53:01.962359

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcfb9293fd61'
down_revision: Union[str, Sequence[str], None] = 'c13b0c9de31f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident_feedback',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_feedback_incident_id'), 'incident_feedback', ['incident_id'], unique=True)
    op.create_table('incident_service_report',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.Column('deleted_date', sa.DateTime(), nullable=True),
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('labor_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_service_report_incident_id'), 'incident_service_report', ['incident_id'], unique=True)
    op.drop_constraint(op.f('device_push_token_push_token_key'), 'device_push_token', type_='unique')
    op.drop_index(op.f('ix_device_push_token_push_token'), table_name='device_push_token')
    op.create_index(op.f('ix_device_push_token_push_token'), 'device_push_token', ['push_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_push_token_push_token'), table_name='device_push_token')
    op.create_index(op.f('ix_device_push_token_push_token'), 'device_push_token', ['push_token'], unique=False)
    op.create_unique_constraint(op.f('device_push_token_push_token_key'), 'device_push_token', ['push_token'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_incident_service_report_incident_id'), table_name='incident_service_report')
    op.drop_table('incident_service_report')
    op.drop_index(op.f('ix_incident_feedback_incident_id'), table_name='incident_feedback')
    op.drop_table('incident_feedback')
    # ### end Alembic commands ###
