export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/auth/login',
    REGISTER: '/auth/register',
    LOGOUT: '/auth/logout',
    PROFILE: '/auth/me',
    PASSWORD: {
      REQUEST_OTP: '/auth/password/request-otp',
      VERIFY_OTP: '/auth/password/verify-otp',
    },
  },
  USER: {
    UPDATE_PROFILE: '/user/me/profile',
    UPDATE_PASSWORD: '/user/me/password',
    EMAIL_CHANGE_REQUEST_OTP: '/user/me/email/change/request-otp',
    EMAIL_CHANGE_VERIFY_OTP: '/user/me/email/change/verify-otp',
    UPDATE_EMAIL: '/user/me/email',
  },
  REPAIR_SHOP: {
    CREATE: '/repair-shop/create',
    ME: '/repair-shop/me',
    MY_DASHBOARD: '/repair-shop/me/dashboard',
    SERVICES: '/repair-shop/services',
    ASSIGN_MY_SERVICES: '/repair-shop/me/services',
    MY_SERVICES: '/repair-shop/me/services',
    UPDATE_MY_PROFILE: '/repair-shop/me/profile',
    UPDATE_MY_LOCATION: '/repair-shop/me/location',
    MY_MECHANICS: '/repair-shop/me/mechanics',
    DELETE_MY_MECHANIC: '/repair-shop/me/mechanics',
    CREATE_MY_INVITATION: '/repair-shop/me/invitation',
    MY_INVITATION: '/repair-shop/me/invitation',
    DELETE_MY_INVITATION: '/repair-shop/me/invitation',
    ADMIN_SHOPS: '/repair-shop/admin/shops',
    ADMIN_SHOP_OVERVIEW_BASE: '/repair-shop/admin/shops',
    ADMIN_SHOP_MECHANICS_BASE: '/repair-shop/admin/shops',
    ADMIN_SHOP_RECENT_SERVICES_BASE: '/repair-shop/admin/shops',
  },
  ASSIGNMENTS: {
    OWNER_PENDING_OFFERS: '/assignments/me/offers/pending',
    OWNER_OFFER_HISTORY: '/assignments/me/offers/history',
    OWNER_ASSIGNMENTS: '/assignments/me/assignments',
    OWNER_OFFER_DETAIL: '/assignments',
    OWNER_SERVICE_REPORT_PDF_SUFFIX: 'service-report/pdf',
    OWNER_SUBMIT_OFFER_SUFFIX: 'submit-offer',
    OWNER_REJECT_SUFFIX: 'reject',
  },
  REALTIME: {
    SHOP_OFFERS_WS: '/realtime/ws/shops/me/offers',
    INCIDENT_WS_BASE: '/realtime/ws/incidents',
    INCIDENT_SNAPSHOT_BASE: '/realtime/incidents',
  },
  WALLET: {
    MY_BALANCE: '/wallet/me/balance',
    MY_TRANSACTIONS: '/wallet/me/transactions',
    TOPUP_QR: '/wallet/me/topups/qr',
    TOPUP_CONFIRM_BASE: '/wallet/me/topups',
  },
} as const;
