export const APP_ROUTES = {
  AUTH_BASE: '/auth',
  AUTH_LOGIN: '/auth/login',
  AUTH_REGISTER: '/auth/register',
  APP_HOME: '/app',
  APP_HOME_ADMIN: '/app/admin',
  APP_ADMIN_REPAIR_SHOPS: '/app/repair-shops',
  APP_HOME_OWNER: '/app/owner',
  APP_OWNER_REQUESTS: '/app/owner/requests',
  APP_OWNER_BALANCE: '/app/owner/balance',
  APP_OWNER_ASSIGNMENTS: '/app/owner/assignments',
  APP_OWNER_MECHANICS: '/app/owner/mechanics',
  APP_OWNER_SHOP_SETTINGS: '/app/owner/shop-settings',
  APP_OWNER_ORDERS: '/app/owner/requests',
  APP_OWNER_HISTORY: '/app/owner/balance',
  APP_HOME_MECHANIC: '/app/mechanic',
  APP_HOME_CLIENT: '/app/repair-shop',
  APP_REPAIR_SHOP: '/app/repair-shop',
  APP_REPAIR_SHOP_SERVICES: '/app/repair-shop/services',
  APP_PROFILE: '/app/profile',
  NOT_FOUND: '/404',
} as const;
