class IncidentWorkflowEvent:
    INCIDENT_STATUS_CHANGED = "incident.status.changed"
    ASSIGNMENT_OFFER_CREATED = "assignment.offer.created"
    ASSIGNMENT_SHOP_NOTIFIED = "assignment.shop.notified"
    ASSIGNMENT_OFFER_SUBMITTED = "assignment.offer.submitted"
    ASSIGNMENT_OFFER_REJECTED = "assignment.offer.rejected"
    ASSIGNMENT_CLIENT_ACCEPTED = "assignment.client.accepted"
    ASSIGNMENT_OFFER_STATUS_CHANGED = "assignment.offer.status_changed"
    ASSIGNMENT_OFFER_EXPIRED = "assignment.offer.expired"
    MECHANIC_STATUS_UPDATED = "mechanic.status.updated"
    MECHANIC_LOCATION_UPDATED = "mechanic.location.updated"
    INCIDENT_REPORT_CREATED = "incident.report.created"
    ASSIGNMENT_FINAL_REPORT_SUBMITTED = "assignment.final_report.submitted"
    PAYMENT_CHECKOUT_CREATED = "payment.checkout.created"
    PAYMENT_COMPLETED = "payment.completed"
